# ============================================================
#  UPDATE WEBSITE TEXT
# ============================================================
#  Reads content.txt and writes the wording into your HTML.
#
#  First run  : creates content.txt from the text already on your site
#  After that : edit content.txt, run this, done
#
#  Run it by double-clicking "Update-Text.bat"
# ============================================================

param([switch]$AutoRun)   # -AutoRun = don't pause at the end (used by Update-Website.ps1)

$ErrorActionPreference = "Stop"
Set-Location (Split-Path $PSScriptRoot -Parent)   # site root is one level up

function Pause-Unless-Auto($msg = "Press Enter to close") {
    if (-not $AutoRun) { Read-Host "`n$msg" | Out-Null }
}

$contentFile = "content.txt"
$htmlFiles = Get-ChildItem -Filter "*.html" | Select-Object -ExpandProperty Name

# Friendly section headings for content.txt, in display order
$groups = [ordered]@{
    "SITE-WIDE  (appears in the footer of every page)" = @("site.footer_tagline","site.email","site.copyright","site.built_with")
    "HOME PAGE  (index.html)"                          = @("home.title","home.subtitle","home.about_heading","home.about_body","home.based_in","home.specialties","home.available","home.works_heading")
    "MEET ME PAGE  (meetme.html)"                      = @("meetme.title","meetme.tagline","meetme.body","meetme.location")
    "GALLERY PAGE  (gallery.html)"                     = @("gallery.title","gallery.intro")
    "PROJECT: AUTOMOTIVE"                              = @("project.automotive.title","project.automotive.role","project.automotive.desc")
    "PROJECT: AVIATION"                                = @("project.aviation.title","project.aviation.role","project.aviation.desc")
    "PROJECT: CONCERTS"                                = @("project.concerts.title","project.concerts.role","project.concerts.desc")
    "PROJECT: FOOD"                                    = @("project.food.title","project.food.role","project.food.desc")
    "PROJECT: FORMULA 1"                               = @("project.f1.title")
    "PROJECT: COMMISSION"                              = @("project.commission.title","project.commission.role","project.commission.desc")
    "PROJECTS PAGE  (projects.html)"                   = @("projects.title","projects.intro")
}

# Text on projects.html is generated by sync-website.ps1, so it is stored here
# rather than read out of the HTML.
$syncOwned = @{
    "projects.title" = "projects"
    "projects.intro" = "A collection of editorial pieces, and deep dives into specific visual stories."
}

function Read-CurrentText {
    $found = @{}
    foreach ($f in $htmlFiles) {
        $c = Get-Content $f -Raw -Encoding UTF8
        foreach ($m in [regex]::Matches($c, '<!--T:([^>]+?)-->(.*?)<!--/T-->', 'Singleline')) {
            $k = $m.Groups[1].Value
            if (-not $found.ContainsKey($k)) { $found[$k] = $m.Groups[2].Value }
        }
    }
    foreach ($k in $syncOwned.Keys) { if (-not $found.ContainsKey($k)) { $found[$k] = $syncOwned[$k] } }
    return $found
}

function New-ContentFile($current) {
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("# ============================================================")
    [void]$sb.AppendLine("#  YOUR WEBSITE TEXT")
    [void]$sb.AppendLine("# ============================================================")
    [void]$sb.AppendLine("#")
    [void]$sb.AppendLine("#  HOW TO USE:")
    [void]$sb.AppendLine("#    1. Change the text UNDER each [heading] below.")
    [void]$sb.AppendLine("#    2. Save this file.")
    [void]$sb.AppendLine("#    3. Double-click 'Update-Text.bat'.")
    [void]$sb.AppendLine("#")
    [void]$sb.AppendLine("#  RULES:")
    [void]$sb.AppendLine("#    - Do NOT change the [heading] lines. They tell the script where the text goes.")
    [void]$sb.AppendLine("#    - Lines starting with # are notes. They are ignored.")
    [void]$sb.AppendLine("#    - Keep each piece of text on ONE line.")
    [void]$sb.AppendLine("#    - To write an & symbol, just type &")
    [void]$sb.AppendLine("#")
    [void]$sb.AppendLine("# ============================================================")
    [void]$sb.AppendLine("")

    foreach ($g in $groups.Keys) {
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("# ------------------------------------------------------------")
        [void]$sb.AppendLine("#  $g")
        [void]$sb.AppendLine("# ------------------------------------------------------------")
        foreach ($k in $groups[$g]) {
            if (-not $current.ContainsKey($k)) { continue }
            [void]$sb.AppendLine("")
            [void]$sb.AppendLine("[$k]")
            [void]$sb.AppendLine($current[$k])
        }
        [void]$sb.AppendLine("")
    }
    Set-Content $contentFile -Value $sb.ToString().TrimEnd() -Encoding UTF8
}

function Read-ContentFile {
    $vals = [ordered]@{}
    $key = $null; $buf = @()
    foreach ($line in (Get-Content $contentFile -Encoding UTF8)) {
        if ($line -match '^\s*#') { continue }
        if ($line -match '^\s*\[([^\]]+)\]\s*$') {
            if ($key) { $vals[$key] = ($buf -join " ").Trim() }
            $key = $matches[1].Trim(); $buf = @()
        } elseif ($key) {
            if ($line.Trim() -ne "") { $buf += $line.Trim() }
        }
    }
    if ($key) { $vals[$key] = ($buf -join " ").Trim() }
    return $vals
}

Write-Host ""
Write-Host "============================================================"
Write-Host "  UPDATE WEBSITE TEXT"
Write-Host "============================================================"
Write-Host ""

$current = Read-CurrentText
if ($current.Count -eq 0) {
    Write-Host "No text markers found in your HTML files." -ForegroundColor Red
    Write-Host "Run '_install-text-markers.ps1' once first."
    Pause-Unless-Auto
    exit 1
}

# ---- first run: create content.txt and stop -------------------------------
if (-not (Test-Path $contentFile)) {
    New-ContentFile $current
    Write-Host "Created 'content.txt' with all $($current.Count) pieces of text from your site." -ForegroundColor Green
    Write-Host ""
    Write-Host "WHAT TO DO NOW:"
    Write-Host "  1. Open content.txt (double-click it - it opens in Notepad)"
    Write-Host "  2. Change any wording you like"
    Write-Host "  3. Save, then run this again to apply it"
    Write-Host ""
    Pause-Unless-Auto
    exit 0
}

# ---- apply -----------------------------------------------------------------
$wanted = Read-ContentFile
if ($wanted.Count -eq 0) {
    Write-Host "content.txt has no text in it. Nothing to do." -ForegroundColor Yellow
    Pause-Unless-Auto
    exit 1
}

$changes = @(); $unknown = @(); $edited = @{}

foreach ($k in $wanted.Keys) {
    $new = $wanted[$k]
    if ($syncOwned.ContainsKey($k)) { continue }   # handled by sync-website.ps1
    if (-not $current.ContainsKey($k)) { $unknown += $k; continue }
    if ($current[$k] -eq $new) { continue }

    $hit = $false
    foreach ($f in $htmlFiles) {
        $c = Get-Content $f -Raw -Encoding UTF8
        $pattern = "(?s)(<!--T:" + [regex]::Escape($k) + "-->).*?(<!--/T-->)"
        if ($c -match $pattern) {
            $c = [regex]::Replace($c, $pattern, { param($m) $m.Groups[1].Value + $new + $m.Groups[2].Value })
            Set-Content $f -Value $c -Encoding UTF8 -NoNewline
            $edited[$f] = $true; $hit = $true
        }
    }
    if ($hit) { $changes += "  $k" }
}

# projects.html is fully REGENERATED by sync-website.ps1, so it cannot hold markers.
# Write everything that page needs into content.projects.txt for sync to read.
$projOut = @("# Auto-generated by Update-Text.ps1 - do not edit by hand.",
             "# Edit content.txt instead, then run Update-Text.bat.")
foreach ($k in $syncOwned.Keys) { if ($wanted.Contains($k)) { $projOut += "$k=$($wanted[$k])" } }
foreach ($k in @("site.footer_tagline","site.email","site.copyright","site.built_with")) {
    if ($wanted.Contains($k)) { $projOut += "$k=$($wanted[$k])" }
}
Set-Content "$PSScriptRoot\content.projects.txt" -Value ($projOut -join "`r`n") -Encoding UTF8

Write-Host ""
if ($changes.Count -eq 0) {
    Write-Host "No changes - your HTML already matches content.txt." -ForegroundColor Green
} else {
    Write-Host "Updated $($changes.Count) piece(s) of text across $($edited.Count) file(s):" -ForegroundColor Green
    $changes | ForEach-Object { Write-Host $_ }
}
if ($unknown.Count -gt 0) {
    Write-Host ""
    Write-Host "These headings in content.txt didn't match anything on the site:" -ForegroundColor Yellow
    $unknown | ForEach-Object { Write-Host "  [$_]" -ForegroundColor Yellow }
    Write-Host "(Check for a typo in the [heading] name.)"
}
Write-Host ""
Write-Host "Open your site to check it looks right, then send the folder"
Write-Host "back to your own PC and push to GitHub."
Write-Host ""
Pause-Unless-Auto
